### ISSUE TITLE
Invalid database url

### ISSUE THREAD

**Issue by David-Lor** [mozilla-services/syncstorage-rs#1511]
Hello there,

I'm trying to run a syncstorage server in Docker, but I'm receiving this error when the server starts:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ApiError { kind: Db(DbError { kind: Common(SyncstorageDbError { kind: Internal("Invalid database url: mysql://syncserver:****@mozillasync_syncstorage_db:3306/syncstorage"), status: 500, backtrace:    0: <syncstorage_db_common::error::SyncstorageDbError as core::convert::From<syncstorage_db_common::error::SyncstorageDbErrorKind>>::from
```

Where `****` is my user password, and it only contains upper/lower letters and numbers, no special characters or symbols. I've tried with and without specifying the port.

The database credentials and connection details are correct, as I can connect to it from other container:

```
bash-4.4# mysql -u syncserver -p'****' -h mozillasync_syncstorage_db -P 3306 -D syncstorage
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.2.0 MySQL Community Server - GPL

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use syncstorage;
Database changed

mysql> create table foo(id int primary key);
Query OK, 0 rows affected (0.43 sec)

mysql> drop table foo;
Query OK, 0 rows affected (1.79 sec)
```

Judging by the error `Invalid database url`, it would seem my URI is incorrect, but I don't see structural differences with the example provided [here](https://github.com/mozilla-services/syncstorage-rs/blob/master/docker-compose.mysql.yaml#L64).

This is my dockercompose:

```yaml
version: "3.4"

services:
  syncstorage:
    image: mozilla/syncstorage-rs:0.14.4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      SYNC_HOST: 0.0.0.0
      SYNC_MASTER_SECRET: ***
      SYNC_SYNCSTORAGE__DATABASE_URL: mysql://syncserver:***@syncstorage_db:3306/syncstorage
      SYNC_TOKENSERVER__DATABASE_URL: mysql://syncserver:***@syncstorage_db:3306/tokenserver
      SYNC_TOKENSERVER__RUN_MIGRATIONS: "true"
    depends_on:
      - syncstorage_db
    networks:
      - backend

  syncstorage_db:
    image: mysql:8.2.0
    volumes:
      - /home/docker/volumes/mozillasync_syncstorage_mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/1-syncserver-initdb.sql:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: root
      MYSQL_USER: syncserver
      MYSQL_PASSWORD: ***
    networks:
      - backend

networks:
  backend:
    external:
      name: backend-overlay
```

**Comment by jackyzy823** [comment]
See https://github.com/mozilla-services/syncstorage-rs/issues/1495 and https://github.com/mozilla-services/syncstorage-rs/issues/1482

**Comment by WAdama** [comment]
At the moment you have to use version 0.13.7 for use with mysql/mariadb. This still works...

**Comment by azoller1** [comment]
I still cant get past this invalid URL error even with version 0.13.7. Using similar compose file as referenced earlier in this thread

**Comment by jrconlin** [comment]
The error [is generated] in `syncstorage-spanner`, which indicates that sync believes you are using spanner for this.  `syncstorage-settings` presumes [you're using spanner if](https://github.com/mozilla-services/syncstorage-rs/blob/de4a77b0bac5968389f73384ab07454be69fe711/syncstorage-settings/src/lib.rs#L153) the database URL begins with `spanner://` [The default](https://github.com/mozilla-services/syncstorage-rs/blob/de4a77b0bac5968389f73384ab07454be69fe711/syncstorage-settings/src/lib.rs#L107-L108) for this is set to `mysql://root...`, so you may have either an environment variable like `SYNC_STORAGE__DATABASE_URL="spanner://..."` (or if you're using a `--config` file `database_url = "spanner://..."`)

**Comment by Unfaehig** [comment]
Is there a reason why syncstorage is going to use spanner?
I mean don't get me wrong but i think a lot of Firefox users are not using Google Chrome to get rid of Google dependencies. When Mozilla is now building Google dependencies into backend functionalities like this here sync private information like bookmarks, extensions etc. doesn't really make sense for me!

**Comment by jrconlin** [comment]
There are a few reasons.

1) MySQL isn't sufficient. Put bluntly, we have lots of experience running MySQL nodes, and at the scale we need to run at, MySQL isn't the answer. Nodes fail, often, which meant that we had a HUGE data loss problem. This is invisible for anyone who has multiple devices, but many folk considered "Sync" to be a Backup service and were sad and upset when they needed to reinstall and all their data was gone because the node failed. (Postgres is a bit better, but not significantly so.)

2) Cost. Put simply, we save a LOT of money by running this on a hosted, distributed database. We don't have to pay for the servers, co-lo space, someone to go push buttons or swap disks, etc. It's the reason that a lot of companies use distributed databases and shared services. As to which service we use, that decision is outside of my pay-grade. For now, we're on GCP. We may move in the future to some other database provided we get a better deal somewhere else. That said, most of the big, distributed databases aren't exactly SQL. They get very close, but they're different. There are a lot of reasons for that, but it's the hand we have to work with, so we do. 

Our problems are not your problems (and frankly, I really hope that you never have to deal with our problems). 

All that said, Spanner is just a big SQL-like database, so there's no difference in what gets stored. It's still completely end-to-end encrypted, so all anyone outside of your devices can tell it's just blobs of random crap. The syncstorage server basically does some auth, and then just stores and retrieves those blobs of "stuff" based on the [API](https://mozilla-services.readthedocs.io/en/latest/storage/apis-1.5.html). (Honestly? Anyone could write their own syncserver if they wanted to.) syncstorage is basically just a bunch of buckets with a slightly smart way of storing and retrieving them.

**Comment by Unfaehig** [comment]
@jrconlin Thanks for taking the time and going into details really appreciate it!
I totally get the point that MySQL is may be not the best for huge amount of data with a lot of requests. You guys need to think in difference scales. I just really hope this will not mean MySQL will be deprecated in this project. It has a huge potential using Rust and give the ability to self host your services which is quite unique in this area!

**Comment by jrconlin** [comment]
@Unfaehig Honestly? I hope not either. That said, the decision isn't mine to make. I can definitely argue that we need to have the level of data abstraction that lets us migrate to a different storage engine system, so that part will definitely stick around, but as for the MySQL work, that's a bit less certain. We really need the community who uses that to support it because it's impossible to argue for the time (and money) to do it internally. There are already [some wonderful soul](https://github.com/mozilla-services/syncstorage-rs/pull/1520) that is stepping up to the challenge, and I'd encourage anyone to help her out. Even if you don't know how to write rust code, you could help with writing documents or cleaning up comments. If you know python, help with the testing code. If you know docker configs, you can help create something better than the confusing test specific configurations we have. I'm happy to provide pointers and tips when I can. 

There's the [Firefox Sync](https://chat.mozilla.org/#/room/#sync:mozilla.org) matrix board on chat.mozilla.org that you can use to coordinate if you want. 

Frankly, please put us to shame and make something better than what we've would have come up with.

**Comment by jyundt** [comment]
@jrconlin 
Apologies for necro-ing this issue, but if mysql isn't currently supported, what is the recommended method for self hosting a `syncstorage-rs` instance? 

Asking because I spent an embarrassing amount of time troubleshooting `syncstorage-rs` + mysql until I found this older issue.

I think the [sqlite PR](https://github.com/mozilla-services/syncstorage-rs/pull/1520) has gone stale and it's not clear to me based on recent PRs if postgres support is available yet.

**Comment by felfert** [comment]
MySQL and MariaDB **ARE** supported. The info above is obsolete. With the released version 0.21.1, there was an incompatibility with MariaDB, but that has been fixed in master (not released yet). If you want to use 0.21.1 with MariaDB, apply [this patch](https://github.com/felfert/syncstorage-rs-rpm/blob/main/syncstorage-rs-mariadb-compat.patch) before building.
For the same reason (switch to diesel_async), the Database-URL-parameters had to be changed. A table of those changes can be found [here](https://github.com/mozilla-services/syncstorage-rs/issues/1843#issuecomment-3410340603).

Regarding postgres availability: I would recommend to wait for the next release. Until then, stick to 0.21.1

If you need a working (native, with MySQL/MariaDB support) installation: I have packaged 0.21.1 for Fedora and RHEL [here](https://copr.fedorainfracloud.org/coprs/felfert/syncstorage-rs/) and for Ubuntu 24.04 LTS [here](https://launchpad.net/~felfert/+archive/ubuntu/syncstorage-rs).

**Comment by jyundt** [comment]
I suspect this is PEBKAC , but I'm still getting an `Invalid database url` error with mysql and mariadb, even when running $LATEST (56c21e0fef9a6464257a822d9910813d37cbfede). However, I think this behavior is limited to the published container.


Example using the published docker container:
```
jyundt@athena:~$ podman run --net host --rm -ti --entrypoint="/bin/bash" docker.io/mozilla/syncstorage-rs:56c21e0fef9a6464257a822d9910813d37cbfede 
app@athena:~$ SYNC_SYNCSTORAGE__DATABASE_URL='mysql://syncstorage:hunter2@127.0.0.1/syncstorage'  bin/syncserver

thread 'main' panicked at syncserver/src/main.rs:63:55:
called `Result::unwrap()` on an `Err` value: ApiError { kind: Db(DbError { kind: Common(SyncstorageDbError { kind: Internal("Invalid database url: mysql://syncstorage:hunter2@127.0.0.1/syncstorage"), status: 500, backtrace:    0: <syncstorage_db_common::error::SyncstorageDbError as core::convert::From<syncstorage_db_common::error::SyncstorageDbErrorKind>>::from
             at /app/syncstorage-db-common/src/error.rs:160:24
      <T as core::convert::Into<U>>::into
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/convert/mod.rs:768:9
      syncstorage_db_common::error::SyncstorageDbError::internal
             at /app/syncstorage-db-common/src/error.rs:72:47
   1: syncstorage_spanner::error::DbError::internal
             at /app/syncstorage-spanner/src/error.rs:46:29
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings::{{closure}}
             at /app/syncstorage-spanner/src/manager/session.rs:79:17
      core::option::Option<T>::ok_or_else
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/option.rs:1340:25
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings
             at /app/syncstorage-spanner/src/manager/session.rs:78:14
   2: syncstorage_spanner::manager::deadpool::SpannerSessionManager::new
             at /app/syncstorage-spanner/src/manager/deadpool.rs:39:23
   3: syncstorage_spanner::pool::SpannerDbPool::new_without_migrations
             at /app/syncstorage-spanner/src/pool.rs:45:23
   4: syncstorage_spanner::pool::SpannerDbPool::new
             at /app/syncstorage-spanner/src/pool.rs:33:9
   5: syncserver::server::Server::with_settings::{{closure}}
             at /app/syncserver/src/server/mod.rs:271:27
      syncserver::main::{{closure}}
             at /app/syncserver/src/main.rs:63:49
   6: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1049:44
      tokio::task::local::LocalSet::with::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:795:13
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
   7: tokio::task::local::LocalSet::with
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:793:17
      <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1039:22
      tokio::task::local::LocalSet::run_until::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:691:19
      <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/future/future.rs:124:9
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:70
      tokio::task::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:167:5
      tokio::task::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:133:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:25
      tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:432:19
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:741:44
      tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:68
      tokio::runtime::context::scoped::Scoped<T>::set
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/scoped.rs:40:9
   9: tokio::runtime::context::set_scheduler::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:38
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
      tokio::runtime::context::set_scheduler
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:17
      tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:27
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:729:24
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:200:33
      tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/runtime.rs:65:16
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:188:9
      tokio::runtime::runtime::Runtime::block_on_inner
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:356:52
      tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:330:18
  10: tokio::task::local::LocalSet::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:648:12
      actix_rt::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/runtime.rs:138:20
      actix_rt::system::SystemRunner::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/system.rs:244:17
      syncserver::main
             at /app/syncserver/src/main.rs:27:1
  11: core::ops::function::FnOnce::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:250:5
      std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:152:18
  12: std::rt::lang_start::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:206:18
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:284:21
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:175:24
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:171:5
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start
 }), status: 500, backtrace:    0: <syncstorage_spanner::error::DbError as core::convert::From<syncstorage_spanner::error::DbErrorKind>>::from
             at /app/syncstorage-spanner/src/error.rs:95:33
   1: <T as core::convert::Into<U>>::into
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/convert/mod.rs:768:9
      syncstorage_spanner::error::DbError::internal
             at /app/syncstorage-spanner/src/error.rs:46:64
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings::{{closure}}
             at /app/syncstorage-spanner/src/manager/session.rs:79:17
      core::option::Option<T>::ok_or_else
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/option.rs:1340:25
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings
             at /app/syncstorage-spanner/src/manager/session.rs:78:14
   2: syncstorage_spanner::manager::deadpool::SpannerSessionManager::new
             at /app/syncstorage-spanner/src/manager/deadpool.rs:39:23
   3: syncstorage_spanner::pool::SpannerDbPool::new_without_migrations
             at /app/syncstorage-spanner/src/pool.rs:45:23
   4: syncstorage_spanner::pool::SpannerDbPool::new
             at /app/syncstorage-spanner/src/pool.rs:33:9
   5: syncserver::server::Server::with_settings::{{closure}}
             at /app/syncserver/src/server/mod.rs:271:27
      syncserver::main::{{closure}}
             at /app/syncserver/src/main.rs:63:49
   6: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1049:44
      tokio::task::local::LocalSet::with::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:795:13
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
   7: tokio::task::local::LocalSet::with
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:793:17
      <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1039:22
      tokio::task::local::LocalSet::run_until::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:691:19
      <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/future/future.rs:124:9
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:70
      tokio::task::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:167:5
      tokio::task::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:133:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:25
      tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:432:19
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:741:44
      tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:68
      tokio::runtime::context::scoped::Scoped<T>::set
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/scoped.rs:40:9
   9: tokio::runtime::context::set_scheduler::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:38
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
      tokio::runtime::context::set_scheduler
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:17
      tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:27
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:729:24
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:200:33
      tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/runtime.rs:65:16
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:188:9
      tokio::runtime::runtime::Runtime::block_on_inner
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:356:52
      tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:330:18
  10: tokio::task::local::LocalSet::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:648:12
      actix_rt::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/runtime.rs:138:20
      actix_rt::system::SystemRunner::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/system.rs:244:17
      syncserver::main
             at /app/syncserver/src/main.rs:27:1
  11: core::ops::function::FnOnce::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:250:5
      std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:152:18
  12: std::rt::lang_start::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:206:18
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:284:21
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:175:24
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:171:5
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start
 }), backtrace:    0: <syncstorage_spanner::error::DbError as core::convert::From<syncstorage_spanner::error::DbErrorKind>>::from
             at /app/syncstorage-spanner/src/error.rs:95:33
   1: <T as core::convert::Into<U>>::into
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/convert/mod.rs:768:9
      syncstorage_spanner::error::DbError::internal
             at /app/syncstorage-spanner/src/error.rs:46:64
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings::{{closure}}
             at /app/syncstorage-spanner/src/manager/session.rs:79:17
      core::option::Option<T>::ok_or_else
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/option.rs:1340:25
      syncstorage_spanner::manager::session::SpannerSessionSettings::from_settings
             at /app/syncstorage-spanner/src/manager/session.rs:78:14
   2: syncstorage_spanner::manager::deadpool::SpannerSessionManager::new
             at /app/syncstorage-spanner/src/manager/deadpool.rs:39:23
   3: syncstorage_spanner::pool::SpannerDbPool::new_without_migrations
             at /app/syncstorage-spanner/src/pool.rs:45:23
   4: syncstorage_spanner::pool::SpannerDbPool::new
             at /app/syncstorage-spanner/src/pool.rs:33:9
   5: syncserver::server::Server::with_settings::{{closure}}
             at /app/syncserver/src/server/mod.rs:271:27
      syncserver::main::{{closure}}
             at /app/syncserver/src/main.rs:63:49
   6: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1049:44
      tokio::task::local::LocalSet::with::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:795:13
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
   7: tokio::task::local::LocalSet::with
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:793:17
      <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:1039:22
      tokio::task::local::LocalSet::run_until::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:691:19
      <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/future/future.rs:124:9
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:70
      tokio::task::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:167:5
      tokio::task::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:133:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:742:25
      tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:432:19
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:741:44
      tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:68
      tokio::runtime::context::scoped::Scoped<T>::set
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/scoped.rs:40:9
   9: tokio::runtime::context::set_scheduler::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:38
      std::thread::local::LocalKey<T>::try_with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:315:12
      std::thread::local::LocalKey<T>::with
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/local.rs:279:20
      tokio::runtime::context::set_scheduler
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context.rs:176:17
      tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:829:27
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:729:24
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:200:33
      tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/runtime.rs:65:16
      tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/current_thread/mod.rs:188:9
      tokio::runtime::runtime::Runtime::block_on_inner
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:356:52
      tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:330:18
  10: tokio::task::local::LocalSet::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/local.rs:648:12
      actix_rt::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/runtime.rs:138:20
      actix_rt::system::SystemRunner::block_on
             at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/system.rs:244:17
      syncserver::main
             at /app/syncserver/src/main.rs:27:1
  11: core::ops::function::FnOnce::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:250:5
      std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:152:18
  12: std::rt::lang_start::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:206:18
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:284:21
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:175:24
      std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
      std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:171:5
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start
, status: 500 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
app@athena:~$ 


```

Example of using your PPA .deb with the same DB / same DB connection string (working as expected):
```
root@athena:~# mysql -u syncstorage -h 127.0.0.1 -phunter2 syncstorage
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 104
Server version: 12.1.2-MariaDB-ubu2404 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [syncstorage]> exit
Bye
root@athena:~# dpkg -s syncstorage-rs
Package: syncstorage-rs
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 35833
Maintainer: Fritz Elfert <fritz@fritz-elfert.de>
Architecture: amd64
Version: 0.21.1-20
Depends: libc6 (>= 2.34), libgcc-s1 (>= 4.2), libmariadb3 (>= 3.0.0), libssl3t64 (>= 3.0.0), zlib1g (>= 1:1.2.3.4)
Recommends: mariadb-server | mysql-server, apache2 | nginx | caddy
Conffiles:
 /etc/default/syncserver 7cc5301bfaaf041f2665f0029f54eb6e
 /etc/syncserver/syncserver.toml 7673b64df08dd76a0710e75bbd8ae5e0
Description: FireFox syncserver
 This is Mozilla's new syncserver written in Rust
root@athena:~# SYNC_SYNCSTORAGE__DATABASE_URL='mysql://syncstorage:hunter2@127.0.0.1/syncstorage' /usr/libexec/syncserver 
^C^Croot@athena:~# 
```

**Comment by felfert** [comment]
Judging from the backtrace showing this:
```
1: syncstorage_spanner::error::DbError::internal
             at /app/syncstorage-spanner/src/error.rs:46:29
```

That image has been built with `spanner` DB support, not mysql or postgres.

Perhaps there is a misunderstanding:
By stating "MySQL and MariaDB ARE supported", I meant at compile time. The type of the supported DB is selected at compile time by selecting so called rust `features` when running cargo like this:

`cargo build --features=syncstorage-db/mysql` enables mysql/mariadb support
`cargo build --features=syncstorage-db/spanner` enables spannerdb support
`cargo build --no-default-features --features=syncstorage-db/postgres` enables postgres support

**Important:** Only **one** of the above can be selected at any point. If you attempt to build with multiple of the above features, you will get a compile error, telling you exactly that.

This selection enables/disables compilation of different sources. Therefore, this selection cannot be changed at runtime by selecting another DB-URL.

**Comment by felfert** [comment]
Oh, and you can visit https://hub.docker.com/r/mozilla/syncstorage-rs/tags and click on any tag to see the layers. I did not find yours, but if you look at the [latest one](https://hub.docker.com/layers/mozilla/syncstorage-rs/56c21e0fef9a6464257a822d9910813d37cbfede/images/sha256-5ef4bb5e770033e9dc93911b197b4e31c5a921750d33012a0e0093eba1452d7f) (as of this writing) you see at the 2nd line:

`ARG SYNCSTORAGE_DATABASE_BACKEND=spanner`

Which confirms my assumption.

**Comment by jyundt** [comment]
Ahh got it, thanks for the clarification. I did _not_ realize that DB support was selected at build time.

And yeah, [the link you provided](https://hub.docker.com/layers/mozilla/syncstorage-rs/56c21e0fef9a6464257a822d9910813d37cbfede/images/sha256-5ef4bb5e770033e9dc93911b197b4e31c5a921750d33012a0e0093eba1452d7f) is the container image I was testing with, thanks for confirming it was built with spanner support.

I recognize you may not be able to answer this, but is there appetite to support non-spanner Docker containers? (e.g. mysql and postgres)? If so, I can open a new issue for tracking.

**Comment by felfert** [comment]
I don't know. I personally don't like the bloat that comes with containers. And since I happen to have a host with a LAMP stack anyway, I packaged it natively so I can run it on that host.

**Comment by kqvanity** [comment]
Ran into same issue with default `test` credentials with the default `docker-compose.mysql.yaml`

**Comment by felfert** [comment]
So what exact image are you using? On hub.docker.com, they only have spanner and postgres images [here](https://hub.docker.com/r/mozilla/syncstorage-rs/tags) No mysql. In that docker-compose.mysql.yaml, the image is referenced by a variable named `SYNCSTORAGE_RS_IMAGE` so it depends how docker compose is invoked.

Also: You did read the comment at the start of that file, did you?

**Comment by kqvanity** [comment]
> So what exact image are you using?

MySql-based one. I'm building from source as instructed by the docs

> Also: You did read the comment at the start of that file, did you?

Just did :(

I'll keep an eye for when it's ready for production

**Comment by taddes** [comment]
Hi @jyundt & @felfert , hope you're both well. By default, we use Spanner as a backend for sync and you can specify which tokenserver and sync backend you wish to use. As to your question @jyundt , we have just completed Postgres support for sync & tokenserver and are building a Docker image. In the same DockerHub repo [here](https://hub.docker.com/layers/mozilla/syncstorage-rs/9fbeaee2062477630907afbac5f49e8ca5f1b87d-postgres/images/sha256-0f1803be194663746116f1ff4c61803bebbe4f6e98aa898ae7b64e5bdb76a382), for example. The previous sync image used spanner by default and will now have a `-spanner` suffix, as the Postgres version will have `-postgres`. Note that this is a new feature and we are still doing some additional testing, have documentation to add on building and usage, etc.

**Comment by jyundt** [comment]
@taddes ah got it, thank you for the clarification. I'll check out these newer postgres containers and will open new issues if I find anything.

**Comment by clouserw** [comment]
We have new documentation on deploying with docker at https://mozilla-services.github.io/syncstorage-rs/how-to/how-to-run-with-docker.html if it helps.  Closing based on the most recent comments.
